#ifndef _CONFIG_H_
#define _CONFIG_H_
#define LAUNCHER_PORT 145
#define CSN_UC_PORT 146
#define CSN_BC_PORT 129
#define DHT_UC_PORT 147
#define MULTIHOP_PORT 135
#define MULTIHOP_DHT_PORT 136
#define WL_UC_PORT 137
#define WL_BC_PORT 138
#define WL_SEARCH_PORT 139
#define MULTIHOP_QUERY_PORT 140
#endif

